export const badgeColors = {
    html: 'bg-orange-500 text-white',
    css: 'bg-blue-500 text-white',
    javascript: 'bg-yellow-400 text-black',
    typescript: 'bg-blue-400 text-white',
    react: 'bg-cyan-400 text-white',
    nextjs: 'bg-black text-white',
    vue: 'bg-green-500 text-white',
    nuxtjs: 'bg-green-700 text-white',
    svelte: 'bg-orange-600 text-white',
    astro: 'bg-purple-500 text-white',
    ejs: 'bg-yellow-600 text-white',
    nodejs: 'bg-green-600 text-white',
    express: 'bg-green-800 text-white',
    nestjs: 'bg-red-600 text-white',
    adonisjs: 'bg-indigo-800 text-white',
    hapi: 'bg-yellow-600 text-black',
    django: 'bg-green-800 text-white',
    flask: 'bg-gray-700 text-white',
    springboot: 'bg-green-700 text-white',
    ruby: 'bg-red-500 text-white',
    rails: 'bg-crimson-600 text-white',
    php: 'bg-indigo-500 text-white',
    laravel: 'bg-red-500 text-white',
    mysql: 'bg-blue-700 text-white',
    postgresql: 'bg-indigo-600 text-white',
    mongodb: 'bg-green-700 text-white',
    sqlite: 'bg-blue-900 text-white',
    firebase: 'bg-yellow-500 text-black',
    prisma: 'bg-lime-400 text-black',
    sequelize: 'bg-sky-700 text-white',
    tailwind: 'bg-teal-400 text-white',
    bootstrap: 'bg-purple-700 text-white',
    daisyui: 'bg-pink-400 text-white',
    gsap: 'bg-green-500 text-white',
    framer: 'bg-black text-white',
    vite: 'bg-gradient-to-r from-yellow-400 via-pink-500 to-purple-600 text-white',
    git: 'bg-orange-600 text-white',
    github: 'bg-gray-900 text-white',
    gitlab: 'bg-orange-500 text-white',
    docker: 'bg-blue-600 text-white',
    vercel: 'bg-black text-white',
    vscode: 'bg-blue-500 text-white',
    figma: 'bg-pink-500 text-white',
    canva: 'bg-blue-400 text-white',
    postman: 'bg-orange-500 text-white',
    'gemini api': 'bg-gradient-to-r from-blue-400 to-fuchsia-500 text-white',
    'chatgpt api': 'bg-gradient-to-r from-emerald-400 to-green-600 text-white',
    greenfoot: 'bg-green-800 text-white',
    python: 'bg-yellow-300 text-black',
    java: 'bg-red-600 text-white',
    kotlin: 'bg-purple-500 text-white',
    dart: 'bg-blue-300 text-white',
    c: 'bg-blue-800 text-white',
    'c++': 'bg-blue-900 text-white',
    go: 'bg-sky-500 text-white',
    rust: 'bg-orange-700 text-white',
    linux: 'bg-black text-white',
    borland: 'bg-blue-900 text-white',
};

export const MyProjects = [
    {
        title: 'SERASI',
        subtitle: 'Sistem Manajemen Rapat Sistem Informasi',
        number: 1,
        description: 'SERASI adalah aplikasi berbasis web yang dikembangkan untuk menyederhanakan dan mendigitalisasi manajemen rapat di departemen Sistem Informasi. Aplikasi ini dirancang khusus untuk memudahkan administrator rapat dalam mengelola seluruh siklus rapat, mengotomatiskan tugas-tugas penting seperti membuat undangan rapat, mencatat kehadiran, mendokumentasikan notulen rapat, dan menyimpan dokumen terkait. Hasilnya, SERASI secara signifikan meningkatkan efisiensi dan organisasi dibandingkan dengan proses manual.',
        image: '/public/serasi1.png',
        badges: ['nodejs', 'express', 'tailwind', 'ejs', 'github', 'prisma'],
        keyFeatures: [
            'Manajemen absensi rapat secara digital dan terintegrasi.',
            'Pengelolaan jadwal dan agenda rapat dengan sistem yang terorganisir.',
            'Pencatatan dan pengarsipan notulensi rapat secara otomatis.',
            'Penyimpanan dokumen rapat dalam satu tempat yang mudah diakses.',
            'Dukungan ekspor data rapat ke dalam format PDF untuk dokumentasi resmi.'
        ],
        demoLink: 'https://serasi.siunand.my.id/',
        codeLink: 'https://github.com/Radithya21/SERASI',
        semester: 4,
        shape: 'wide'
    },
    {
        title: 'Sistem Penunjang Keputusan',
        subtitle: 'SPK Pemilihan Pantai Terbaik di Kota Padang',
        number: 2,
        description: 'Mengembangkan Sistem Pendukung Keputusan (SPK) berbasis web sebagai inisiatif mandiri, yang ditujukan untuk Dinas Pariwisata Provinsi Sumatera Barat. Aplikasi inovatif ini dirancang untuk memudahkan proses identifikasi dan pemeringkatan pantai-pantai terbaik di Kota Padang. Dengan mengimplementasikan metode TOPSIS (Technique for Order Preference by Similarity to Ideal Solution), sistem ini secara obyektif mengevaluasi pantai-pantai berdasarkan berbagai kriteria yang relevan seperti kebersihan, fasilitas, aksesibilitas, dan lain-lain. Hasil dari sistem ini memberikan rekomendasi yang jelas, tidak hanya menyederhanakan pengambilan keputusan pariwisata bagi dinas, tetapi juga menawarkan data konkret sebagai dasar untuk program pemeliharaan dan peningkatan kualitas pantai-pantai yang berada di peringkat bawah, sehingga mendukung pengembangan pariwisata berkelanjutan di Sumatera Barat.',
        image: '/public/spk.png',
        badges: ['sqlite', 'react', 'express', 'sequelize', 'github'],
        keyFeatures: [
            'Evaluasi pantai berdasarkan berbagai kriteria seperti kebersihan, fasilitas, dan aksesibilitas.',
            'Pemberian rekomendasi peringkat pantai terbaik secara otomatis.',
            'Antarmuka web interaktif yang memudahkan pengguna dalam meninjau hasil pemeringkatan.',
        ],
        demoLink: '#',
        codeLink: 'https://github.com/Radithya21/topsis-beach-selector',
        semester: 4,
        shape: 'tall'
    },
    {
        title: 'My Portofolio',
        subtitle: 'Website Portofolio Pribadi',
        number: 3,
        description: 'Portofolio pribadi interaktif dengan desain modern berbasis React, Tailwind CSS, dan Gsap.',
        image: '/public/porto.png',
        badges: ['react', 'tailwind', 'framer', 'vite', 'github', 'html', 'css', 'javascript', 'gsap',],
        keyFeatures: [
            'Desain responsif dan modern menggunakan Tailwind CSS.',
            'Animasi interaktif dan transisi halus dengan GSAP.',
            'Navigasi halaman yang intuitif dan user-friendly.',
            'Menampilkan proyek-proyek unggulan beserta detail dan gambar.',
        ],
        demoLink: '#',
        codeLink: '#',
        semester: 4,
        shape: 'wide'
    },
    {
        title: 'Finding Treasure',
        subtitle: 'Game Berbasis Java OOP',
        number: 4,
        description: 'sebuah game petualangan bawah laut interaktif yang dibuat menggunakan Greenfoot dan diimplementasikan sepenuhnya dengan prinsip-prinsip Pemrograman Berorientasi Objek (OOP) di Java. Dalam game ini, pemain berperan sebagai penyelam yang memiliki misi untuk mengumpulkan emas dan kunci yang tersembunyi. Untuk mencapainya, pemain harus menavigasi lingkungan bawah laut yang penuh dengan rintangan, termasuk menghindari ikan-ikan yang ganas dan serangan proyektil berapi-api dari tengkorak misterius. Proyek ini secara efektif menunjukkan kemampuan saya dalam merancang logika permainan yang kompleks, mengelola interaksi objek, dan menerapkan paradigma OOP untuk menciptakan pengalaman bermain game yang menantang dan imersif.',
        image: '/public/gamePBO.png',
        badges: ['java', 'canva', 'github', 'greenfoot'],
        keyFeatures: [
            'Permainan petualangan bawah laut dengan misi mengumpulkan emas dan kunci.',
            'Lingkungan interaktif dengan berbagai rintangan seperti ikan ganas dan proyektil tengkorak.',
            'Penerapan prinsip Pemrograman Berorientasi Objek (OOP) dalam seluruh mekanisme permainan.',
            'Interaksi antar objek game yang kompleks dan dinamis.',
            'Desain level yang menantang untuk meningkatkan pengalaman bermain yang imersif.'
        ],
        demoLink: 'https://www.greenfoot.org/scenarios/33942',
        codeLink: 'https://github.com/Radithya21/Finding-Treasure-Game',
        semester: 3,
        shape: 'tall'
    },
    {
        title: 'Law Firm App',
        subtitle: 'Aplikasi Manajemen Rapat via CLI',
        number: 5,
        description: 'Law Firm App adalah aplikasi Command Line Interface (CLI) yang dirancang untuk memudahkan pengelolaan kasus di firma hukum. Aplikasi ini menyediakan fitur CRUD (Create, Read, Update, Delete) untuk data kasus, serta dilengkapi dengan statistik kasus menggunakan operasi matematika sederhana. Dengan antarmuka berbasis teks yang intuitif, pengguna dapat menambah, melihat, memperbarui, dan menghapus data kasus secara efisien, serta mendapatkan ringkasan statistik kasus secara langsung.',
        image: '/public/lawfirm.png',
        badges: ['java', 'mysql', 'github'],
        keyFeatures: [
            'Menambah, melihat, memperbarui, dan menghapus data kasus (CRUD) secara efisien.',
            'Menampilkan statistik kasus dengan operasi matematika sederhana.',
            'Antarmuka CLI yang sederhana dan mudah digunakan.',
            'Integrasi dengan database MySQL untuk penyimpanan data yang terstruktur.'
        ],
        demoLink: '#',
        codeLink: 'https://github.com/Radithya21/TB_PBO',
        semester: 3,
        shape: 'wide'
    },
    {
        title: 'Jam Store App',
        subtitle: 'Aplikasi POS Toko Selai via Borland',
        number: 6,
        description: 'untuk toko selai yang dikembangkan menggunakan Borland C++. Aplikasi ini memungkinkan pengelolaan stok bahan dan produk, pencatatan transaksi penjualan, serta pencetakan struk secara otomatis. Dengan antarmuka yang mudah digunakan, aplikasi ini sangat cocok untuk bisnis kecil hingga menengah yang membutuhkan sistem kasir offline yang ringan dan efisien.',
        image: '/public/jamstore.jpg',
        badges: ['c++', 'borland', 'github'],
        keyFeatures: [
            'Manajemen stok bahan baku dan produk secara real-time.',
            'Proses transaksi penjualan dengan input antrian pelanggan.',
            'Pencetakan struk pembelian secara otomatis.',
            'Fitur pencarian, filter, dan rekap harian penjualan.'
        ],
        demoLink: '#',
        codeLink: 'https://github.com/Radithya21/jamstore-POS',
        semester: 1,
        shape: 'tall'
    },
];

export const MyCertificates = [
    // {
    //     title: 'Web Development Fundamentals',
    //     issuer: 'Coursera',
    //     date: '2023',
    //     image: 'https://placehold.co/400x240/1e3a8a/fff?text=Web+Dev+Cert',
    //     credentialId: 'WDF2023001'
    // },
    
]; 